### ISSUE TITLE
yaml for github action?

### ISSUE THREAD

**Issue by ozbillwang** [jdrouet/docker-on-ci#7]
could you please share the yaml file for github action?

**Comment by ozbillwang** [comment]
Not sure why it was removed from current latest commit (https://github.com/jdrouet/docker-on-ci/commit/751caaaaeca33e8db01e15c417f29b2f2d457049)

```
name: build

on: [push]

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build and push
        run: make build-push
        env:
          CI_NAME: github
```

Can you explain?
